import { lazy } from 'react';

export const Intros = lazy(() => import('components/ui/start-plan/Intros'));
export const Forum = lazy(() => import('components/ui/start-plan/Forum'));
export const Part1Intro = lazy(() => import('./Part1/Part1Intro'));
export const Q1 = lazy(() => import('./Part1/Q1'));
export const Part2Intro = lazy(() => import('./Part2/Part2Intro'));
export const Q2 = lazy(() => import('./Part2/Q2'));
export const Part3Intro = lazy(() => import('./Part3/Part3Intro'));
export const Q3 = lazy(() => import('./Part3/Q3'));
export const Q4 = lazy(() => import('./Part3/Q4'));
export const Q5 = lazy(() => import('./Part3/Q5'));
export const Q6 = lazy(() => import('./Part3/Q6'));
export const Q7 = lazy(() => import('./Part3/Q7'));
export const Q8 = lazy(() => import('./Part3/Q8'));
export const Q9 = lazy(() => import('./Part3/Q9'));
export const Q10 = lazy(() => import('./Part3/Q10'));
export const Q11 = lazy(() => import('./Part3/Q11'));
export const Q12 = lazy(() => import('./Part3/Q12'));
export const Part4Intro = lazy(() => import('./Part4/Part4Intro'));
export const Q13 = lazy(() => import('./Part4/Q13'));
export const Q14 = lazy(() => import('./Part4/Q14'));
export const Q15 = lazy(() => import('./Part4/Q15'));
export const Q16 = lazy(() => import('./Part4/Q16'));
export const Q17 = lazy(() => import('./Part4/Q17'));
